spring:
  application:
    name: StorePay

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USER}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_HIBERNATE_DDL_AUTO}

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}